### ISSUE TITLE
Progresso

### ISSUE THREAD

**Issue by EnzoFranzini1** [EnzoFranzini1/avaliacaoandroid#2]
**TODO**

---

- [x] **RecyclerView**
  - [x] Desenvolvimento do Layout
  - [x] Preenchimento com todas as informações necessárias de rede
  - [x] Scroll dinâmico páginado
  - [x] Barra de progresso de carregamento ao iniciar aplicação

---

- [x] **Tratamento de dados**
  - [x] Implementação do Retrofit e RXJava
  - [x] Implementação do gson converter factory
  - [x] Retorno adequado das informações do ponto final
  - [x] Criação da Data Class
  - [x] Estruturação da Data Class

---

- [x] **Interface e comportamento da barra inferior e superior**
  - [x] Implementação da barra de navegação inferior
  - [x] Implementação da barra de navegação superior
  - [x] Adição dos listeners da barra de navegação inferior
  - [x] Adição dos listeners da barra de navegação superior
